services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data # Bind mount for database
      - ./.env:/app/.env # Bind mount for .env file
    container_name: queue-bot
    restart: always
    command: ["npm", "run", "docker:start"]
    logging:
      options:
        max-size: "10m"
        max-file: "5"
